# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      neo4j:
        # Docker Hub image
        image: neo4j:latest
        env:
          # install GDS at startup
          NEO4J_AUTH: neo4j/rel
          NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
        ports:
          # Maps bolt port
          - 7687:7687
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # 15.x not working yet
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: lerna bootstrap
      - run: lerna link
      - run: lerna run build
      - run: lerna run test:ci
        env:
          NEO4J_URI: localhost:7687
          NEO4J_USERNAME: neo4j
          NEO4J_PASSWORD: rel
